### ISSUE TITLE
How move target to moving end position?

### ISSUE THREAD

**Issue by ShockWave2048** [KyryloKuzyk/PrimeTween#14]
Hi Kyrylo!
How i can change end value over tween update?
(Need move actor transform to moving camera, speed based motion, PositionAtSpeed())

**Comment by KyryloKuzyk** [comment]
Hi!
It is not possible to change the endValue while the animation is playing for several reasons:
- Changing the endValue mid-way will modify the speed because the duration is [calculated](https://github.com/KyryloKuzyk/PrimeTween#speed-based-animations) at the moment of starting the tween based on the distance.
- Changing the endValue will cause the easing curve to look different.
- Adding this feature will break the consistency of Tween API. Tween struct knows nothing about the type of animation, so there is no way to validate at compile time if a user has specified the correct endValue type.

A possible alternative would be to stop the previous tween and start a new one with the desired endValue. However, if the camera's position is updated every frame, then the ease curve will not look correct. Here is an example:
<details>
<summary>Click to expand</summary>

```csharp
using UnityEngine;
using PrimeTween;

public class FollowExample : MonoBehaviour {
    [SerializeField] Transform target;
    [SerializeField] float speed = 10;
    [SerializeField] Ease ease;
    Vector3 targetPos;
    Tween tween;

    void Update() {
        if (targetPos != target.position) {
            targetPos = target.position;
            tween.Stop();
            tween = Tween.PositionAtSpeed(transform, targetPos, speed, ease);
        }
    }
}
```

</details>

The correct approach to these kinds of problems is called 'damping', and it can be implemented with something like [Vector3.SmoothDamp](url). Currently, PrimeTween doesn't have the 'damping' feature and only solves the 'tweening' problem, that is, interpolating the values between startValue and endValue that are known in advance. I'll consider adding the damping feature in future versions.

**Comment by ShockWave2048** [comment]
Thank you very much for the detailed explanation!

**Comment by KyryloKuzyk** [comment]
One possible way to 'fake' the animation towards the moving target would be [like this](https://forum.unity.com/threads/primetween-high-performance-animations-and-sequences.1479609/page-2#post-9403583).
