### ISSUE TITLE
Assert method call in Sequence causes allocation

### ISSUE THREAD

**Issue by pepperwood998** [KyryloKuzyk/PrimeTween#49]
Hi, im facing some runtime allocation when using Sequence, specifically there is some Assert method call that create the allocation.

![image](https://github.com/KyryloKuzyk/PrimeTween/assets/27287529/e51da2f6-5daa-4253-83ea-38960012063d)

I'm profiling in the Unity Editor(Play Mode). Will this also happen in build(ex: Android)? Please let me know if you need more information, I'm kind of in a hurry.

**Comment by KyryloKuzyk** [comment]
This allocation happens only the first time you call the `Sequence.Chain()` method because the `EqualityComparer<int>.Default` is created. All subsequent calls will not allocate GC. Static variables are not garbage collected, meaning they don't cause spikes because the Garbage Collector doesn't care about them. But they still show up in Profiler.

A similar behavior may observed in other places of PrimeTween. For example, the first time you call `Tween.Position()`, a static delegate that animates position is created and you'll see GC Alloc in Profiler. But all subsequent calls will reuse the same delegate. This delegate is deallocated when the app terminates, so technically speaking this should not be counted as GC allocation.

Also, assertions are only enabled in Editor or Development builds. You can disable them with the PRIME_TWEEN_DISABLE_ASSERTIONS scripting define if you wish to benchmark PrimeTween. Please also ensure you're measuring the performance on a real device, not in the Editor, because the results may differ by a lot.
