### ISSUE TITLE
Unity Package Manager support

### ISSUE THREAD

**Issue by Dasparion** [KyryloKuzyk/PrimeTween#7]
Would be great to add package manager support for this plugin. Using package manager allows for cleaner updates and workflows.

**Comment by KyryloKuzyk** [comment]
PrimeTween already installs via Package Manager! Although, Asset Store has its caveats, so the library installs with the help of tgz archive. This lets me take the best from both words: it’s easy to find the demo scene because it installs into Assets folder, and the library itself installs into to the Packages. 

There are also reasons that I described here: https://forum.unity.com/threads/primetween-high-performance-animations-and-sequences.1479609/#post-9231630

**Comment by KyryloKuzyk** [comment]
@SudoCat I totally understand the 'thumbs down' reaction. However, PrimeTween is not an open-source product in the classical sense of this word. It's an Asset Store product that is currently available for free, but may become paid in the future. And I don't want to give false expectation to my users by distributing PrimeTween as a scoped registry package. It would be dishonest to revoke access in the future for users who installed via UMP's scroped registry.

I understand that the current distribution method of Asset Store is not perfect, and I would love to see the UPM support added to Asset Store in the future. But for now, I'm trying to make the installation as seamless as possible with the tools available to the Asset Store publisher.
